### ISSUE TITLE
Info abount MndtId and DtOfSgntr fields

### ISSUE THREAD

**Issue by itajackass** [w2c/sepa-sdd-xml-generator#8]
Hi this is not a bug, it's a reequest info.
I need to know that's is mndtid and DtOfSgntr fields. I can't find documentation online... i found only faqs that explain is a mandatory unique identifier with his date (in italian: IDENTIFICATIVO UNIVOCO ASSEGNATO DAL CREDITORE AL MANDATO SOTTOSCRITTO DAL DEBITORE)

I can assign a random values? cause my app doesn't collect this data info.

**Comment by Churro** [comment]
Hi,

A good documentation is, e.g., provided here: https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC130-08%20SDD%20Core%20C2B%20IG%202017%20V1.0.pdf

See page 25 for descriptions of both `MndtId` and `DtOfSgntr`. The document also clearly states what type of value is expected for each of these two fields.
